name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  PullRequest_Master:
    name: Test, Build And Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.0.0
      with:
        version: 3.1.100
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Sonar
      run: dotnet tool install --tool-path . dotnet-sonarscanner --version 4.8.1
    - name: Update PATH
      run: echo "/home/runner/work/SampleAPI_For_GithubAction/SampleAPI_For_GithubAction" >> $GITHUB_PATH
    - name: Generate Code Coverge File
      run: dotnet test SampleAPI.Test/SampleAPI.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Build Server Shutdown
      run: dotnet build-server shutdown
    - name: Sonar Scanner Begin
      run: dotnet sonarscanner begin /k:SampleAPI /v:1.0  /n:SampleAPI  /d:sonar.host.url=https://sonarcloud.io /o:testrepockeditor  /d:sonar.login=${{ secrets.token }} /d:sonar.coverage.exclusions=**Tests*.cs /d:sonar.cs.opencover.reportsPaths=SampleAPI.Test/coverage.opencover.xml
    - name: Code Rebulild
      run: dotnet build SampleAPI.sln --no-incremental
    - name: Sonar Scanner End
      run: dotnet sonarscanner end /d:sonar.login=${{ secrets.token }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_SampleAPI }}
